[workspace]
members = [
    "crash_backend",
    "plinko_backend",
    "dice_backend",
    "roulette_backend",
    "life1_backend",
    "life2_backend",
    "life3_backend",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1