[package]
name = "plinko_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"

[dev-dependencies]
rand = "0.8"