[package]
name = "life3_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10"
ic-cdk = "0.19"
serde = { version = "1.0", features = ["derive"] }
